### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by silkevicious**

### CODE REVIEW

**Comment by alexAubin** [comment]
Many thanks :stuck_out_tongue:  !

**Comment by silkevicious** [comment]
@alexAubin after the website got updated, i got a "not found" text instead of the main page at yunohost.org , while other pages like "apps" don't load data. Is there something wrong in my translation? Or is it necessary to translate every yunohost/doc page?

**Comment by alexAubin** [comment]
Hmno it should fallback to english by default ? Do some pages work though ?

**Comment by alexAubin** [comment]
Uh well I can kinda reproduce this bug ... Sounds like it's been there for a while, dunno why we havent heard of this earlier :/ I need to finish a few things before looking into this, please harass me if I forgot :s

**Comment by silkevicious** [comment]
>  please harass me if I forgot :s


with pleasure! :stuck_out_tongue_closed_eyes: 

Ok see you later!

**Comment by alexAubin** [comment]
Heylo !

Follow-up of this discussion : I had a look and it's way more complicated than I thought. I was able to fix a few weird/broken behaviors (in particular for when javascript is disabled) but that wasn't addressing the issue at stake here. There are various different use case and edge cases and it's difficult to define something that works in all cases.

Anyway, I think at least the code includes assumptions that, for each enabled languages, at least the 'index' and 'default' page should be defined. (Ideally also 'help' I think)

So I disable 'it' for now ... and see later if there are any issue (right now it sounds like if i switch my browser to spanish, it doesnt automatically use spanish, dunno why :| ... in french it works...)

**Comment by silkevicious** [comment]
Ok no problem. I may go behind and start translating those files in the mean time (when i'll have a bit of spare time)
Thank you! :wink:

**Pull request merged**
