### PR TITLE
Create accounting_ar.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by alexAubin** [comment]
Uh, actually the english (and french?) version of this page is a bit outdated since no account is required to contribute anymore ...

c.f. https://yunohost.org/#/accounting (which redirects to https://yunohost.org/#/write_documentation )

(the corresponding page is here : https://github.com/YunoHost/doc/blob/master/accounting.md )

So not sure what to do with this :s

**Comment by ghost** [comment]
Hello @alexAubin,

This page is related to Simone as seen on : https://github.com/YunoHost/Simone/tree/master/_pages

**Comment by zamentur** [comment]
Simone could effectively be used by other project than yunohost... Even if we (the yunohost team) are not completely satisfy of it.

So i merge this as a micro decision.

**Comment by alexAubin** [comment]
Yes but still, there is no account system anymore ...

**Comment by zamentur** [comment]
You're right! So we should update all messages

**Comment by zamentur** [comment]
I can't push in this patch... I suggest we close it as the string translated is outdated

**Pull request closed without merging**
